### ISSUE TITLE
Correct readme

### ISSUE THREAD

**Issue by topkecleon** [LibreLabUCM/HALIX9000#1]
Hi! topkecleon here, author of otouto (or as you call it, mokubot). otouto is not based on yagop's telegram-bot in any way, except perhaps spiritually. The codebase is 100% original. Please correct your readme. :)

**Comment by ender-null** [comment]
+1

report for disinfo

**Comment by improbabilityfield** [comment]
+1

**Comment by Akronix** [comment]
Hi!
I'm sorry for the misunderstanding I found both design similar (also same language) and I thought that otouto was actually a port to the new API from telegram-bot.
I apologize for this and I'll update the README file ASAP.

**Comment by topkecleon** [comment]
Thanks for the quick response!
I see that the readme has been edited. :)
(Although the bottom of the readme still contains the misleading info.)

**Comment by topkecleon** [comment]
Thanks for the quick response! :)

**Comment by Akronix** [comment]
Hi there!

Do you mean this?

> ## Thanks
> 
> Thanks to @topkecleon for developing this awesome bot.
> 
> Also, thanks to @yagop for starting telegram-bot, first codebase of HALIX 9000.

The second thanks refers to our first version of HALIX 9000, HALIX 9000 and HALIX 9001 to be more precise, which is using the telegram-bot based on telegram-cli ([see fork repo](https://github.com/LibreLabUCM/telegram-bot)) and it's still running and being used in telegram ([username: @halix_9001](https://telegram.me/HALIX_9001)).

Now, we are moving to the new API thanks to your great job and this will be our HALIX 9002 ([see about.lua file](https://github.com/LibreLabUCM/HALIX9000/blob/LLU/plugins/about.lua) )

I hope this clarify the bottom of the README, or do you think it's still too confusing??

**Comment by topkecleon** [comment]
No, I'm sorry, I was looking at an outdated version of the page. x'D
Everything's good. Again, thanks for the quick response.
